### ISSUE TITLE
Missing files about environment variables referenced in docs/source/contributing/contributing-dev-environment.md

### ISSUE THREAD

**Issue by cfelder** [ILLGrenoble/visa-docs#3]
referenced files:

docs/source/contributing/
- deployment_environment_variables_api_server
- deployment_environment_variables_jupyter_proxy
- deployment_environment_variables_accounts

do not exist.

**Comment by stuartcaunt** [comment]
This repository is used to generate the docs at visa.readthedocs.io. You'll find that the page works correctly here:
https://visa.readthedocs.io/en/latest/contributing/contributing-dev-environment.html

**Comment by cfelder** [comment]
My bad, thanks for pointing me in the right direction. I was just used to read the markdown file directly in GitHub.
